---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - earayu.github.io.earayu.github.io
  resources:
  - tictactoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - earayu.github.io.earayu.github.io
  resources:
  - tictactoes/finalizers
  verbs:
  - update
- apiGroups:
  - earayu.github.io.earayu.github.io
  resources:
  - tictactoes/status
  verbs:
  - get
  - patch
  - update
